#!/bin/bash

source init-kubectl

add_entry_for_workload() {
    ns=$1
    SERVERPOD=$(./bin/kubectl -n${ns} get pod -l app=spire-server -o jsonpath="{.items[0].metadata.name}")
    # AGENTSPIFFEID=$(./bin/kubectl -n${ns} exec ${SERVERPOD} -- /opt/spire/bin/spire-server agent list | grep "SPIFFE ID" | awk '{print $4}')
    CLUSTER_NODE_SPIFFEID="spiffe://example.org/k8s-workload-registrar/example-cluster/node"
    WORKLOAD_POD=$(./bin/kubectl -n${ns} get pod -l app=example-workload -o jsonpath="{.items[0].metadata.name}")
    if ./bin/kubectl -n${ns} exec ${SERVERPOD} -- /opt/spire/bin/spire-server entry create \
    -spiffeID spiffe://example.org/ns/default/sa/default \
    -parentID ${CLUSTER_NODE_SPIFFEID} \
    -selector k8s:image-signature-subject:mvtms@cesar.org.br \
    -selector k8s:ns:${ns} \
    -selector k8s:pod-name:${WORKLOAD_POD} ;then
        return
    fi
    fail-now "Failed creating entry for workload "
}

add_entry_for_workload spire
