#!/bin/sh

source init-kubectl
source check_for_workload_svid

check_for_workload_svid_multiple_containers "spiffe://example.org/ns/default/sa/default/workload-multiple-containers" example-multiple-containers example-multiple-containers-1

if [ "${DONE}" -eq 1 ]; then
    log-info "SPIFFE ID found."
elif [ "${DONE}" -eq 0 ]; then
    fail-now "timed out waiting for workload to obtain credentials."
else
    fail-now "failed to check for svid"
fi
