#!/bin/bash

source init-kubectl

if [ -z "$SUCCESS" ]; then
   ./bin/kubectl -nspire logs deployment/spire-server --all-containers || true
   ./bin/kubectl -nspire logs daemonset/spire-agent --all-containers || true
   ./bin/kubectl -nspire logs deployment/example-workload-signed --all-containers || true
   ./bin/kubectl -nspire logs deployment/example-workload-unsigned --all-containers || true
fi

export KUBECONFIG=
./bin/kind delete cluster --name k8stest
